[package]
name = "li"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
colored = "2.1.0"
enum-as-inner = "0.6.0"
human-panic = "2.0.0"
indexmap = "2.2.6"
itertools = "0.13.0"
rustyline = "14.0.0"
thiserror = "1.0.61"
